management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
      base-path: /
      path-mapping:
        health: /health
        info: /info
        # prometheus: /metrics
        metrics: /actuator/metrics
  security:
      enabled: false
  health:
    defaults:
      enabled: true

server:
  port: 8080

# prometheus
endpoints:
  prometheus:
    path: metrics
  metrics:
    enabled: false